import argparse
import json
from hamu_tool.dataset import DataLoader
from hamu_tool.utils import CorpusReader
from sentence_transformers import CrossEncoder
from tqdm import tqdm
from utils import get_total_line

def score_qrel(dataset : str, generator : str, version : str) -> None:
    """Filters prompt-query pairs generated by the LLM.

    Args:
        dataset (str): Name of the dataset.
        generator (str): Name of the generator.
        version (str): Version of the prompt to filter.
    """
    doc_reader = DataLoader.load(f'beir/{dataset}')
    query_reader = CorpusReader(f'data/{dataset}/query.{generator}.{version}.idx')
    cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')
    total_size = get_total_line(f'data/{dataset}/query.{generator}.{version}.jsonl')
    with open(f'data/{dataset}/qrel.{generator}.{version}.jsonl', 'r', encoding='utf-8') as fp_qrel, \
        open(f'data/{dataset}/sqrel.{generator}.{version}.jsonl', 'w', encoding='utf-8') as fp_sqrel:
        for line in tqdm(fp_qrel, desc='Filter pq', total=total_size):
            data = json.loads(line.strip())
            query = query_reader[data['qid']]['text']
            doc = doc_reader.get_doc(data['did'])
            doc = (doc['title'] + ' ' + doc['text']).strip()
            score = cross_encoder.predict([query, doc]).tolist()
            dump = json.dumps({'qid': data['qid'], 'did': data['did'], 'score': score})
            fp_sqrel.write(f'{dump}\n')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset', type=str, required=True)
    parser.add_argument('--generator', type=str, required=True)
    parser.add_argument('--version', type=str, required=True)
    args = parser.parse_args()

    score_qrel(args.dataset, args.generator, args.version)
